import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "Nextjs App",
    template: "%s | Umer",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col bg-slate-900 text-white`}
      >
        <header className="text-4xl font-bold bg-slate-500 text-white text-center p-2">
          This the Header of App
        </header>
        <div className="flex flex-col justify-center items-center h-screen">
          {children}
        </div>
        <footer className="text-4xl font-bold text-white bg-gradient-to-b from-slate-500 to-slate-700 text-center p-2">
          This is the footer of app
        </footer>
      </body>
    </html>
  );
}
