import Link from "next/link";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
  title: {
    // This will ignore the template defined in the Layout component of app
    absolute: "Blogs",
  },
  description: "Generated by create next app",
};

const BlogPage = () => {
  return (
    <>
      <h1 className="text-2xl font-bold text-blue-700">Blog</h1>
      <button className="border bg-blue-500 px-3 py-1 rounded-md m-2 hover:bg-blue-400/80">
        <Link href="/">Take me to Home</Link>
      </button>
      <button className="border bg-blue-500 px-3 py-1 rounded-md m-2 hover:bg-blue-400/80">
        <Link href="blog/first">Take me to First Blog</Link>
      </button>
      <button className="border bg-blue-500 px-3 py-1 rounded-md m-2 hover:bg-blue-400/80">
        <Link href="blog/second">Take me to Second Blog</Link>
      </button>
    </>
  );
};

export default BlogPage;
